#!/usr/bin/env bash

set -eu

f () {
    find \
        "$WD" \
        -type f \
        -not -path "$WD/node_modules/*" \
        -not -path "$WD/out/*" \
        -name "$1"
}

f "*.js" | parallel "echo {} && jsfmt {}"
f "*.html" | parallel "echo {} && htmlfmt {}"
f "*.glsl" | parallel "echo {} && clang-format -i {}"

python "$WD/shared/codegen.py"
