#!/usr/bin/env bash

set -eu

jsfmt "$WD/shared/script.js"
htmlfmt "$WD/index.html"
find "$WD" \
    -type f \
    -not -path "$WD/node_modules/*" \
    -not -path "$WD/out/*" \
    -name "*.glsl" \
    | parallel "echo {} && clang-format -i {}"

python "$WD/shared/codegen.py"
